### ISSUE TITLE
Imports from node_modules are not included

### ISSUE THREAD

**Issue by ajafff** [timocov/dts-bundle-generator#1]
Consider the following code:

```ts
import {OnInit} from "@angular/core";
class MyComponent implements OnInit {
    ngOnInit() {};
}
```

### Expected output:
```ts
import {OnInit} from "@angular/core";
declare class MyComponent implements OnInit {
    ngOnInit(): void;
}
```

### Actual output:
```ts
declare class MyComponent implements OnInit {
    ngOnInit(): void;
}
```
This results in an error when importing this generated declaration file, because `OnInit` cannot be found.

**Comment by timocov** [comment]
Hi @ajafff,

sorry for late reply. I need to have a look into this case to fix it.

**Comment by timocov** [comment]
@ajafff what do you think about the following case:
```ts
import { Observable } from 'rxjs/Observable';
```
vs
```ts
import { Observable } from 'rxjs';
```
?

According types for rxjs both cases is valid and seems that it should not break something when for source
```ts
import { Observable } from 'rxjs/Observable';
export type MyType = Observable;
```
the output will be 
```ts
import { Observable } from 'rxjs';
export type MyType = Observable;
```

I guess a library should export all types from entry file but not sure if is it true in common case.

So, according this I have several solutions (because in one project we can have both imports - from specific file and from root):
1. Always import type from specific file (where type is declared)
2. Always import type from `main` file of the library (and assume that library will export this type from `main` file).

**Comment by ajafff** [comment]
Always importing from the package root makes sense. At least I cannot think of any package that doesn't work that way.

**Comment by timocov** [comment]
The new version will be published tomorrow. Thanks!
