### ISSUE TITLE
Enable "auto" behavior for libraries omitted from `allowedTypesLibraries`, `importedLibraries`, and `inlinedLibraries`

### ISSUE THREAD

**Issue by cspotcode** [timocov/dts-bundle-generator#129]
What happens with a third-party library if it's not specified in any of `allowedTypesLibraries`, `importedLibraries`, nor `inlinedLibraries`, but those 3 arrays are specified in the config file?

I assumed that the library would be handled automatically.  Instead, it is neither imported nor inlined.  This means if I import type `Options`, then the output .d.ts tries to refer to `Options`, but the type is completely missing.

Is this behavior intentional?

Here's an example: https://github.com/cspotcode/repros/tree/dts-bundle-generator-ora

**Comment by timocov** [comment]
> I assumed that the library would be handled automatically. Instead, it is neither imported nor inlined. This means if I import type Options, then the output .d.ts tries to refer to Options, but the type is completely missing.

That's because you specify `allowedTypesLibraries`, `importedLibraries` and `inlinedLibraries` as _an empty array_. By default that options are `undefined`, which means "default behaviour" which is kind of detect it "automatically". Just try to drop them from your config and see whether it helps.

I thought that the default behaviour is import what can be imported, reference with types is it's from "types" folder (either `node_modules/@types` or from `typesRoot` from tsconfig) and inline if it's a local file (inside a repo basically, but I'd say just "non-external"). Thus, default behaviour should fit almost all (or the most of) cases.

> What happens with a third-party library if it's not specified in any of allowedTypesLibraries, importedLibraries, nor inlinedLibraries, but those 3 arrays are specified in the config file?

`allowedTypesLibraries` and `importedLibraries` were added a long time ago when the tool didn't understand imports properly and couldn't handle them correctly all time (it can handle some of them, but not all actually). Nowadays I think it's much better and you don't need to specify that options at all if it's work for you.

The only exception I know is when you want to control what libraries you used in every case exactly. That means, that you don't want tom import some library, so you can specify all other libraries in your config and whenever "restricted" library will be added to a bundle, the generation will be failed so can handle it in your CI.

**Comment by cspotcode** [comment]
Sorry for the delayed response.  This makes sense.  I was imagining where I needed to force a single library to be switched from "inline" to "import", but now I understand that "import" is the default.  So it is never needed to force from "inline" to "import", it is only needed to switch from "import" to "inline."
