### ISSUE TITLE
Make typescript peer dependency

### ISSUE THREAD

**Issue by mgambati** [timocov/dts-bundle-generator#157]
I was trying to use `ts-patch` and `typescript-transform-paths` when I realized that ts-patch's install is not patching the typescript on this project because it's not a peer dependency.

There's any reason for this? Doesn't this make sense to allow the user to control the version it uses?

**Comment by timocov** [comment]
What package manager and typescript version do you use? Afaik due `dedupe`'ing `typescript` should be moved to the top of your node_modules.

Also, moving typescript does not help for npm@7 for instance since it installs peer dependencies as well so it doesn't change anything.

> Doesn't this make sense to allow the user to control the version it uses?

You already can do that by specifying your typescript version in package.json file, because the tool uses [any supported version](https://github.com/timocov/dts-bundle-generator/blob/296018a217ddc0fb6c89fd71b6ba0b811266adc0/package.json#L20).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
