### ISSUE TITLE
Retain TSDoc comments

### ISSUE THREAD

**Issue by TxHawks** [timocov/dts-bundle-generator#165]
The current behavior is that Top-level comments are stripped away:

```ts
// input:
/**
 * Foo type description
 * /
type Foo = {
  /**
   *  bar prop description
   * /
  bar:  string;
};

// output:
export declare type Foo = {
  /**
   *  bar prop description
   * /
  bar:  string;
};
```

Which is a problem when wanting to use the top level comment blocks as code hints or to feed into a documentation generator.

It would be great if docblock comments could be retained.

**Comment by timocov** [comment]
@TxHawks we have tests for that and it seems that they are all passed https://github.com/timocov/dts-bundle-generator/blob/19feb85f6b120327d677d29fc6d9ffa03feb3411/tests/e2e/test-cases/save-jsdoc/output.d.ts#L19-L22. Can you check the correctness of jsdoc and if they are correct then create a repro for that please?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.

**Comment by nartallax** [comment]
@timocov as I discovered, this behavior can be observed if `"removeComments": true` is present in tsconfig.json.
I have this option turned on because I don't want comments in my generated JS code (most of the comments are for library developer and not for library user anyway), but when generating .d.ts I want to have the comments because that's documentation for user.
Is it possible to add option to dts-bundle-generator that will override `"removeComments": true` and retain comments just for .d.ts? Or maybe you can suggest another solution?

**Comment by timocov** [comment]
Well, I think the best solution here is to create another tsconfig, extend it from your one and override this setting. Did you try this?

**Comment by nartallax** [comment]
I just had a hope that dts-bundle-generator will have such useful option.

Okay, thanks, I'll do it that way.

**Comment by timocov** [comment]
Also related to https://github.com/timocov/dts-bundle-generator/issues/137

**Comment by keyiis** [comment]
@timocov If possible, I also hope to add this function.like `gulp-typescript`
```
require("gulp-typescript").createProject("tsconfig.json",{"removeComments": false});
```
