### ISSUE TITLE
`d.ts` missing property.

### ISSUE THREAD

**Issue by aboveyunhai** [timocov/dts-bundle-generator#176]
Hello, @timocov  
first thx you for your hard work to create this package. it was pretty convenient to bundle a single ts without pain.
I installed `dts-bundle-generator` globally, and clone the following package,
and then add ` npm i @types/react --save-dev` to fix the missing dependency.
https://github.com/chakra-ui/chakra-ui/tree/main/packages/visually-hidden

After the generation without any problems, I get the following `.d.ts` files, it's very legit. 
```ts
// Generated by dts-bundle-generator v6.0.0

import * as React from 'react';

/**
 * Styles to visually hide an element
 * but make it accessible to screen-readers
 */
export declare const visuallyHiddenStyle: React.CSSProperties;
/**
 * Visually hidden component used to hide
 * elements on screen
 */
export declare const VisuallyHidden: import("@chakra-ui/system").ChakraComponent<"span", {}>;
/**
 * Visually hidden input component for designing
 * custom input components using the html `input`
 * as a proxy
 */
export declare const VisuallyHiddenInput: import("@chakra-ui/system").ChakraComponent<"input", {}>;

export {};

```

But when I check the original files, I found out that there are some properties with `literal` was missing from the `.d.ts` files. 
https://github.com/chakra-ui/chakra-ui/blob/a0de717c98e574e73f8a444f576fc738907230ab/packages/visually-hidden/src/visually-hidden.tsx#L9

May I know why the part of properties was strip away after creation.

My tsconfig:
```json
{
    "lib": ["dom", "esnext"],
    "allowSyntheticDefaultImports": true,
    "jsx": "react"
}
```

**Comment by aboveyunhai** [comment]
To give some background behinds my intention, I currently want to use generator to create `d.ts` for monaco editor.  This was based on vs-code.
![image](https://user-images.githubusercontent.com/35160613/142715842-6eb87ae3-6851-4362-b2a3-2c0a11f4a1e7.png)
![image](https://user-images.githubusercontent.com/35160613/142715831-7ee1c341-cd28-4e05-93dc-c7406300359f.png)
It was amazing close!
My expected result is 
```ts
export declare const visuallyHiddenStyle: React.CSSProperties = {
  border: "0px",
  clip: "rect(0px, 0px, 0px, 0px)",
  height: "1px",
  width: "1px",
  margin: "-1px",
  padding: "0px",
  overflow: "hidden",
  whiteSpace: "nowrap",
  position: "absolute",
};
```
In fact, after I manually add the missing part. Both are equivalent.

**Comment by timocov** [comment]
Hi @aboveyunhai , if you look closer than you'll see that the code you expect is not valid since in typings variables couldn't have initializers:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAD0ljgBMk0AbFIuNCAOwGd4AbsF4BXFCxYBPABLAGTbgGUYklkgBciYjAB0AYUWKACjjBJYwJLzgBeOAG9ycOACNoTKJoBEABjDUvABonThZgMG8iDAAKP2pAuDiEpMT-AEogkIALJGAAcyyYbwBGf0znAHc5GCySsuDnEHY84G5vAFpSgIa4MBR5VrzvOPK4CAFzTBYICu8suQVRivmYJEU+tA04L24ZqBQwUcheYBhgHm8UF14IFhFVzIBfUiA

![image](https://user-images.githubusercontent.com/3112183/142722688-59c147ae-cd27-4f42-b8fb-b75db12f33db.png)

Your variable already have a type specifier, which is `React.CSSProperties`, that's why the tool uses it. And this is exactly what the compiler produces as d.ts for your variable:

![image](https://user-images.githubusercontent.com/3112183/142722765-4b7662e4-2f7e-4d44-97f4-f775b771dac6.png)

**Comment by aboveyunhai** [comment]
@timocov thx, so based on what you mean, this kinds of initializer is invalid in typescript and it's more act like a description hint in this case. Am I right?
Or it's straight up a mistake?

**Comment by timocov** [comment]
> this kinds of initializer is invalid in typescript 

@aboveyunhai Not exactly. This kind of initializer is invalid in _declaration files_ only since they make no sense for anybody It doesn't matter what values are there, the more important is _what types_ (this is the purpose of typings). Declaration files are about types, not about an actual values.

> it's more act like a description hint in this case

Not sure that get what you meant here.

**Comment by aboveyunhai** [comment]
> > this kinds of initializer is invalid in typescript 
> 
> @aboveyunhai Not exactly. This kind of initializer is invalid in _declaration files_ only since they make no sense for anybody It doesn't matter what values are there, the more important is _what types_ (this is the purpose of typings). Declaration files are about types, not about an actual values.
> 
> > it's more act like a description hint in this case
> 
> Not sure that get what you meant here.

Thx, my bad, you are right. I forgot it's declaration file and mess it up with regular typescript files.
