### ISSUE TITLE
publish latest version

### ISSUE THREAD

**Issue by danmarshall** [timocov/dts-bundle-generator#18]
Hello, thanks for this library 👍 
It appears there is some new code in the repo that has not yet published to NPM@0.6.1
Is it ready to publish a patch or minor version?
Thanks!
-Dan

**Comment by timocov** [comment]
Hi Dan,

thanks you for your attention 🙂! I am happy to know that someone use this library except me and my team.

Yes, there are some new code in master (fixes and tests) not published to npm yet.

Actually no one needed new version so that's why I have not published it.

I need some time to prepare new release. I hope it will be ready in a day.

**Comment by danmarshall** [comment]
Great! 🥇  
I was glad to find this library indeed. It's hard to believe that we need to tool around this issue of declaration files and bundles.

I am currently experiencing the bug where all of typescript types appear in my output. I think you've fixed this with an improved regex. I may have some feature requests after that . Cheers!

**Comment by timocov** [comment]
[Version 1.0.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v1.0.0) has been released!
