### ISSUE TITLE
missing enum type export

### ISSUE THREAD

**Issue by Innei** [timocov/dts-bundle-generator#180]
**Bug report**

missing enum type export in dts.

**Input code**

```ts

import { EE, Foo } from "./type";

export const foo: Foo = {
 e: EE.A
}

// type.ts
export enum EE {
  A,B
}

export type Foo = {
  e: EE
}
```

**Expected output**

```ts
// Generated by dts-bundle-generator v6.1.0

export declare enum EE {           // <---------- export
	A = 0,
	B = 1
}
export declare type Foo = {
	e: EE;
};
export declare const foo: Foo;

export {};

```

**Actual output**

```ts
// Generated by dts-bundle-generator v6.1.0

declare enum EE {            // <----------------- miss export 
	A = 0,
	B = 1
}
export declare type Foo = {
	e: EE;
};
export declare const foo: Foo;

export {};

```

**Additional context**

https://github.com/Innei/dts-reproduction

**Comment by timocov** [comment]
Hi @Innei,

your expected output is not correct and here is why - by having `export declare enum EE` it says "your bundle has exported enum EE, which _could be used in JS_" (because enums have generated JS code for them). So with your expected result I should be able to do the following in JS code:

```js
import { EE } from 'you-package';

console.log(EE.A); // prints 0
```
but instead it will raise a reference error because there is no exported member with name `EE`.

From this point of view the tool works exactly how it should work and this is expected and the only right behaviour.

If you want to have an enumeration in your exports list, you need to explicitly state this in your entry point, for example you can use re-export like `export { EE } from './type'` and the tool will mark this enum as exported in the generated d.ts file.

Also, I should note that the above is true for enums, classes and functions as all (because they all have a JS code for them), but not for types, interfaces or `const enums` when `preserveConstEnums` option is disabled.

**Comment by timocov** [comment]
Also please see #56, I think this issue is kind of similar (or duplicate) of it.

**Comment by Innei** [comment]
Thank you.
