### ISSUE TITLE
json import and re-export are ignored?

### ISSUE THREAD

**Issue by HarelM** [timocov/dts-bundle-generator#201]
**Bug report**

**Input code**

Style-spec code of maplibre which export all fields:
https://github.com/maplibre/maplibre-gl-js/blob/1e80b24c6490197cdb61b2538d36c9bb24c4647e/src/style-spec/style-spec.ts

**Expected output**
```
export {
    v8,
    latest,
    format,
    migrate,
    composite,
    derefLayers,
    diff,
    ValidationError,
    ParsingError,
    expression,
    featureFilter,
    convertFilter,
    Color,
    styleFunction as function,
    validate,
    visit
};
```

**Actual output**
```
export declare const visit: {
	eachSource: typeof eachSource;
	eachLayer: typeof eachLayer;
	eachProperty: typeof eachProperty;
};

export {
	createFilter as featureFilter,
	diffStyles as diff,
	styleFunction as function,
	validateStyle as validate,
};
```
**Additional context**
We are importing json files and exporting them as part of the package.
I know there are some discussions with node 16 about how to properly import json file in type/javascript code but still.
Version 6.4 creates an invalid d.ts file and 6.9 creates a file without the `v8` and `latest` members.

I know there are two methods without a name that need to be fixed and will be as part of the effort to create a definition file for this package.

Thanks again for all the hard work invested in this!

**Comment by timocov** [comment]
Hi @HarelM, sorry for late reply. Have you tried to use "correct" types in the project that doesn't have "resolveJsonModules" compiler options enabled? It looks like it might lead to compilation failures and the only way to solve them is to enable that option to disable checking d.ts files.

**Comment by HarelM** [comment]
Can you clarify? I'm not sure I fully understand your comment...

**Comment by timocov** [comment]
@HarelM sure. Let's say you've published a project with the following structure:

**index.d.ts**:
```ts
import * as obj from './obj.json';
export const variable: typeof obj;
```

**obj.json**:
```json
{
	"field": ["any structure here, it does not matter"]
}
```

And now you have a consumer's code that uses your package in their typescript code:

```ts
import { variable } from 'your-package-name';

// do something with `variable`
```

Depending on whether a consumer's code has enabled or disabled `resolveJsonModule` compiler option this code will either compiled or not. So your package might force people to enable this option even though they might not want it (for example their environment might not support it for many reasons).

I don't think that this approach is a good idea (force people to change compiler options because of your package) and that's why I wouldn't recommend you to export anything like that in the production code. It might work for your specific case and probably for most of your users it would work, but there is a chance that it won't. And in this case they have to either disable checking d.ts file by disabling `skipLibCheck` or enabling `resolveJsonModule` but handling and dealing with all the side effects of them.

**Comment by HarelM** [comment]
Thanks for the clarification!
The problem in our case is that this json object/file is very important to our customers and is an essential part of this library.
This json defines the specification of the library's style file, which is similar to a coding language, sort of...
Is there a way to extract type definitions out of a json object/file and have this as part of the d.ts file (thus reducing the need for the compiler flag)?

**Comment by timocov** [comment]
Well, depends on a file you could either write them manually, create a script to generate them somehow (e.g. by using the compiler's API) or use something like https://jvilk.com/MakeTypes/ (but I didn't use it, this is just [the first link in google](https://www.google.com/search?hl=en&q=generate%20types%20for%20json%20typescript)) and inject it in your build steps.

Since this proper looks like out of the scope of this library I'm going to close this issue. If you'll have any questions or updates, feel free to ask them here (this is just for housekeeping purposes).

**Comment by HarelM** [comment]
I think I managed to find a way to solve this.
I'm importing the json file, casting it to `any` and exporting it.
I still didn't look at the generated types, but I hope this will solve the issues you mentioned above for library users...
