### ISSUE TITLE
Is `typeRoots` field ignored?

### ISSUE THREAD

**Issue by mattiaz9** [timocov/dts-bundle-generator#203]
I'm getting the classic error: `Cannot find module './assets/something.svg' or its corresponding type declarations.`

I have the declaration file for the svgs in a typings folder that I also added in the tsconfig:
```json
{
  "compilerOptions": {
    ...
    "typeRoots": ["./typings"],
    ...
  }
}
```

**Comment by timocov** [comment]
> Is typeRoots field ignored? #

No, the tool uses it and there are even 2 tests cases for it https://github.com/timocov/dts-bundle-generator/blob/master/tests/e2e/test-cases/using-custom-types/tsconfig.json and https://github.com/timocov/dts-bundle-generator/blob/master/tests/e2e/test-cases/custom-types-folder/tsconfig.json.

Specifying `typeRoots` isn't enough to load types, it just tells the compiler where to start to lookup the types in addition to `node_modules/@types` (or instead of, not sure). You need to explicitly tell the compiler to load your types. You can do it by using import statement or tripple-slash directive `/// <reference path="" />` (note that you cannot use `<reference types` directive right now because of https://github.com/microsoft/TypeScript/issues/37958). Also, you can use `types` compiler option that should work as well.
