### ISSUE TITLE
"Error: Cannot find symbol for node: Event" when using vuepress

### ISSUE THREAD

**Issue by imjuni** [timocov/dts-bundle-generator#217]
Hi,

first of all: thank for this great product.

I encountered problem while using vuepress. This error raised after that add `vuepress.config.ts` and some of markdown file.

I upload my work on [feature/rollupjs](https://github.com/imjuni/ctix/tree/feature/rollupjs) branch. Problem reproduce that flow.

1. checkout feature/rollup repo
2. install node_modules
3. run command `npm run webpack:prod`

After encountered problem below,

```sh
> ctix@1.3.1 dts-bundle
> dts-bundle-generator dist/src/ctix.d.ts -o dist/ctix.d.ts --no-banner --project ./tsconfig.prod.json

Compiling input files...

Error: Cannot find symbol for node: Event
```
This problem relate to #143 , #173 . 

**Additional context**

Master branch compile without error. Difference between master and feature/rollup that add vuepress and some  of vuepress plugin(vuepress-plugin-mermaid, vuepress-plugin-typedoc)

Thank you!

**Comment by timocov** [comment]
Most likely some of your packages that you installed types for (from `@types` namespace) require `dom` lib provided (or similar) that is not added to your compilation (you don't have specified `lib` compiler option and taking into account that you're extending [`@tsconfig/node16/tsconfig.json` config](https://github.com/tsconfig/bases/blob/7be7a0937cb80761b9e1f64ec5c18c2aa0416530/bases/node16.json#L6) that doesn't have `dom` lib added (and this is expected) it doesn't work. To simply fix this you can restrict automatic loading of any `types` by adding `"types": [],` to your compiler options and it will work fine:

```
$ ./node_modules/.bin/dts-bundle-generator dist/src/ctix.d.ts -o dist/ctix.d.ts --no-banner
Compiling input files...
Processing dist/src/ctix.d.ts
Writing dist/src/ctix.d.ts -> dist/ctix.d.ts
Checking generated files...
Compiler option "skipLibCheck" is disabled to properly check generated output
Done in 1.90s
```

After a quick check I found that the reason is the package `@types/web-bluetooth` that is installed via vuepress:

```
$ npm ls @types/web-bluetooth
ctix@1.3.1
└─┬ vuepress@2.0.0-beta.49
  └─┬ vuepress-vite@2.0.0-beta.49
    └─┬ @vuepress/theme-default@2.0.0-beta.49
      └─┬ @vueuse/core@8.9.4
        └── @types/web-bluetooth@0.0.14
```

You don't see any errors locally because you have `skipLibCheck` compiler option enabled. If you enable it explicitly, you'll get several errors similar to what you're getting from the tool:

```
$ ./node_modules/.bin/tsc --pretty false
node_modules/@types/web-bluetooth/index.d.ts(17,27): error TS2304: Cannot find name 'BufferSource'.
node_modules/@types/web-bluetooth/index.d.ts(18,21): error TS2304: Cannot find name 'BufferSource'.
node_modules/@types/web-bluetooth/index.d.ts(58,45): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(74,23): error TS2304: Cannot find name 'BufferSource'.
node_modules/@types/web-bluetooth/index.d.ts(90,52): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(93,53): error TS2304: Cannot find name 'EventTarget'.
node_modules/@types/web-bluetooth/index.d.ts(101,23): error TS2304: Cannot find name 'BufferSource'.
node_modules/@types/web-bluetooth/index.d.ts(102,35): error TS2304: Cannot find name 'BufferSource'.
node_modules/@types/web-bluetooth/index.d.ts(103,38): error TS2304: Cannot find name 'BufferSource'.
node_modules/@types/web-bluetooth/index.d.ts(106,85): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(107,46): error TS2304: Cannot find name 'EventListenerOrEventListenerObject'.
node_modules/@types/web-bluetooth/index.d.ts(111,38): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(112,40): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(113,40): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(116,46): error TS2304: Cannot find name 'EventTarget'.
node_modules/@types/web-bluetooth/index.d.ts(124,71): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(125,73): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(126,73): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(127,46): error TS2304: Cannot find name 'EventListenerOrEventListenerObject'.
node_modules/@types/web-bluetooth/index.d.ts(141,48): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(148,35): error TS2304: Cannot find name 'EventTarget'.
node_modules/@types/web-bluetooth/index.d.ts(157,81): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(159,46): error TS2304: Cannot find name 'EventListenerOrEventListenerObject'.
node_modules/@types/web-bluetooth/index.d.ts(162,29): error TS2304: Cannot find name 'EventTarget'.
node_modules/@types/web-bluetooth/index.d.ts(165,45): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(169,78): error TS2304: Cannot find name 'Event'.
node_modules/@types/web-bluetooth/index.d.ts(171,46): error TS2304: Cannot find name 'EventListenerOrEventListenerObject'.
```

So if your package is supposed to be used on in nodejs for example, then you need to restrict what types should be loaded into your compilation to these that are supposed to be used in nodejs only (and vice versa for browser-related projects).

Also, having `"types": []` might improve your compilation speed as soon as the compiler will not load all the types and the only used in your app and deps only.

**Comment by imjuni** [comment]
@timocov Thank for your answer that is greatful help!
