### ISSUE TITLE
Support for projects with `allowJs: true`

### ISSUE THREAD

**Issue by josh-** [timocov/dts-bundle-generator#220]
Currently when using `dts-bundle-generator` in a project with `"allowJs": true` set in their `tsconfig.json` that has JavaScript files (`.js` or `.mjs`) in the project, the following error will be generated when running `dts-bundle-generator`:

```
error TS5055: Cannot write file '<filename>' because it would overwrite input file.
```

A failing test case can be found here: https://github.com/timocov/dts-bundle-generator/compare/master...josh-:dts-bundle-generator:allowjs-test-case?expand=1.

Did you have any thoughts on supporting such project configuration? In order to resolve this error would support for `outDir` here be required? https://github.com/timocov/dts-bundle-generator/blob/a0cb4e4e8332f95ad2cce232ccaca1c07064e6f5/src/compile-dts.ts#L21

**Comment by timocov** [comment]
Hi @josh-,

> Did you have any thoughts on supporting such project configuration? 

Well, since the compiler supports this and can generate types for that I think it could be a good addition to the tool, thanks for raising this!

> In order to resolve this error would support for outDir here be required? 

Have you looked into the process why exactly this error is raised by the compiler? Adding support for `outDir` is a little bit tricky because it requires to re-done all the mapping that we have right now (in-memory for modules) and it might be problem (but I haven't looked into yet since it wasn't a critical issue yet).

**Comment by timocov** [comment]
It looks like there is an elegant one-line fix for that 😂 Stay tuned

**Comment by timocov** [comment]
Released in https://github.com/timocov/dts-bundle-generator/releases/tag/v6.13.0

**Comment by josh-** [comment]
> It looks like there is an elegant one-line fix for that 😂 Stay tuned

The best kind of fix, thanks @timocov! 🎉
