### ISSUE TITLE
Add option to remove private and protected methods from the output d.ts file

### ISSUE THREAD

**Issue by rickymohk** [timocov/dts-bundle-generator#223]
Let say I have the following source code in typescript
```ts
type C = "some" | "thing" | "should" | "not" | "be" | "exposed";

class A {
    protected foo(c:C)
    {
        console.log(c);
    }
}

export class B extends A{

    bar()
    {
        this.foo("exposed");
    }
}
```
I get the following output
```ts
// Generated by dts-bundle-generator v6.13.0

declare type C = "some" | "thing" | "should" | "not" | "be" | "exposed";
declare class A {
	protected foo(c: C): void;
}
export declare class B extends A {
	bar(): void;
}

export {};

```

I only want to export `class B`. I get that since class B extends class A so `class A` is also exposed. But `protected foo()` is not callable by user (as class A is not exported, it is not meant to be extended by user), so there is no need to expose `foo`, causing `type C` also get exposed. 

For private methods, I can deal with it by using sharp notation instead. But there is no equivalent for protected methods. I get that the code will be exposed in the js file anyway. But I am going to obfuscate the js file, so I don't want unnecessary easy access to some types that don't have to be in the .d.ts file. Currently I have to manually remove all protected methods and all those referenced type from the output file.

**Comment by timocov** [comment]
Hey @rickymohk,

> But protected foo() is not callable by user (as class A is not exported, it is not meant to be extended by user), so there is no need to expose foo

This is not true. The purpose of "protected" fields is that they are accessible from derived classes but hidden for a public user so technically any protected method could be called by a user. See [this snippet for example](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCYCdoG8BQ0PQA4IPYBcBTYIgE2gDNdcAKASgC5oA3XAS3OQF9UfVRIMACKEEbZoVIBVCKIDC4KNEIAPIgDtSMeEjSZsAVwBGINsGjAwIEAAU8REpIBi1ek1YcU6fZnwALNggAOipaOgBubwwePmBcdQh8aCNEaABeaHVCAHc4RHpIlIQQ1wjoAHpyi1wAWyw2cHw2eOUEPARUfnjE6HIMrNyRMQlpWQQFQQLUUiDLazsCYjIXMPCKqtDobIaQZMILKxBJaD9RQiA).

So for protected fields it is not necessary to add them as you might want to call them from your derived classes.

As for private fields (and protected too) - the only reason why the compiler adds them to the declaration files is to prevent you from overriding it in your derived class. Let's look at the following example:

```ts
export class Foo {
    private bar: number = Math.random();

    public getBar() {
        return this.bar;
    }
}
```

A consumer of this class might want to extend it:

```ts
class Baz extends Foo {
    private bar: string = "my lovely string";

    public getBarValue() {
        return this.bar;
    }
}
```

And now 2 have 2 possible scenarios:
- if `private bar` is in the type declaration of `Foo` class - then the compiler will raise an error, because you cannot override private member. [Link #1](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwCg4S4woBLANxRmDgCMUoAuOAOwFcBbB4KOAF44AWVoALAHRQU7ACYRuACgCUAbkLFSYTgyQUEcAObAYAIWaqCW0qSinOUdnBjiKaSUygbbAX0L+hMjomBYAXnCgdPKYOHhEtuTUtPRebGgwlOxGQnAARNwAnnBIEFTASMUZWUZ5GjZkuvqGJubMAGooSJzAVgm2dg5OLm4eXj6k-r5AA), [link #2](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwCg4S4woBLANxRmDgCMUoAuOAOwFcBbB4KOAF44AWVoALAHRQU7ACYRuACgCUAbkLFSYTgyQUEcAObAYAIWaqCW0qSinOUdnBjiKaSUygbbAX0L+hMjomBYAXnCgdPKYOHhEtuTUtPRebFy8-EJwAEwALAAMeRo2ZLr6hibmzABqKEicwFYJtnYOTi5uHl4+pP6+QA). This is expected and the only correct behaviour in this situation
- if `private bar` is not in the type declaration of `Foo` class - then the compiler will not raise an error and the method `getBarValue` will return a number instead of a string. So this becomes a run-time problem which we all want to avoid of by using typescript I believe.

If you really want to hide some methods/fields from a declaration file, I'd suggest you one of the following solutions:
- "disallow" to extend classes from your library by adding interfaces that you can extend and then expose from your API. In this case you can control what fields and methods you'd like to expose explicitly which adds you more control. But sometimes it is not possible because of the API or other reasons.
- mark fields that you don't want to expose as "internal" and enable `stripInternal` compiler options - in this case the compiler will remove the declaration of such fields from d.ts files. But keep in mind that this solution might break consumer's code as I described above, so it is kinda dangerous. [Link](https://www.typescriptlang.org/play?stripInternal=true#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwCg4S4B6AKgrgAEBLAOxmCgZSTgrONLCjoBuKZnABGKKAC44DAK4BbUSzgBeOAFlhACwB0UFAwAmEeQAoAlAG5CPEmFmikdBHADmwGACEJFgrdIkUB6yrHAwWnRoOuJQ1gEAvoSJQA)
- Kinda mix of the 2 - if you don't want to deal with interfaces you can export your class as `export type` instead and in this case the compiler will not allow to extend your classes. You still need to mark fields as "internal" though.

For similar reasons some time ago I've added an option to handle situations when you have a class in generated file so you can control this and expose only interfaces/types.
