### ISSUE TITLE
Code mode

### ISSUE THREAD

**Issue by euberdeveloper** [timocov/dts-bundle-generator#236]
It would be beautiful to not be forced using the command line made with yargs.

I currently have an esbuild `build.js` file and I would like to add a piece of code generating also the dts there, instead of a separate script in the package.json using your library. 

I think this thing could be easily done, by exporting a function with the same arguments of the cli and then the cli just calls this function

**Comment by timocov** [comment]
The code mode was included into the projects since very first version if I'm not mistaken, see [here](https://github.com/timocov/dts-bundle-generator/blob/fb598977d81103cd3e5a68ff4cbab9e36dc3d738/package.json#L6).

The main entry point [exports a function called `generateDtsBundle`](https://github.com/timocov/dts-bundle-generator/blob/fb598977d81103cd3e5a68ff4cbab9e36dc3d738/src/bundle-generator.ts#L135) that takes entry points config and compilation options, this is similar (or even the same, not quite sure) as what you can specify in a config file. [Here](https://github.com/search?q=generateDtsBundle&type=code) you can see some examples how people are using this API in their scripts.

Ping me if you have any other questions.
