### ISSUE TITLE
[8.1.0] Something went wrong - value cannot be null

### ISSUE THREAD

**Issue by wKovacs64** [timocov/dts-bundle-generator#265]
**Bug report**

dts-bundle-generator stopped working for me as of 8.1.0. Not sure if it's a bug or something I'm doing incorrectly that just happened to work up until now. I'd be happy to do some additional troubleshooting myself, but not sure where to start.

**Input code**

```sh
npx dts-bundle-generator src/hibp.ts
```

**Expected output**

```
Compiling input files...
Processing src/hibp.ts
Writing src/hibp.ts -> src/hibp.d.ts
Checking generated files...
Compiler option "skipLibCheck" is disabled to properly check generated output
```

**Actual output**

```
Compiling input files...
Processing src/hibp.ts

Error: Something went wrong - value cannot be null
```

**Additional context**

Repo: https://github.com/wKovacs64/hibp
Bundle types: `npm run build:types`

**Comment by Shin-Ogata** [comment]
I'm also encountering the same issue. It is also reproduced in v8.1.1.
I realize that this is not the correct fix way, but if I modify `getExportedSymbolsUsingStatement()` as follows, my case works as expected.

- [FILE: src/bundle-generator.ts LINE: 954](https://github.com/timocov/dts-bundle-generator/blob/master/src/bundle-generator.ts#L953-L955)
```diff
	if (symbolsUsingNode === null) {
-		throw new Error('Something went wrong - value cannot be null');
+               return [];
	}
```

**Comment by timocov** [comment]
Looks like I'm missing some compiler internal knowledge here...

@wKovacs64 as a workaround you can create a separate tsconfig for the tool with the following content (e.g. `tsconfig.dts.json`):

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "types": ["node"]
  }
}
```

And then run `npx dts-bundle-generator src/hibp.ts --project tsconfig.dts.json`.

It should work for now while I'm looking for additional information.

@Shin-Ogata are you also using vitest in your project? If so, feel free to replicate the workaround for now (otherwise please share your reproduction so I can check if issues have the same roots).

**Comment by wKovacs64** [comment]
> @wKovacs64 as a workaround you can create a separate tsconfig for the tool with the following content (e.g. `tsconfig.dts.json`):

Thanks, I'll do that for now.

**Comment by Shin-Ogata** [comment]
> @Shin-Ogata are you also using vitest in your project? 
> If so, feel free to replicate the workaround for now (otherwise please share your reproduction so I can check if issues have the same roots).

I don't use vitest, so I cannot apply that workaround.
It seemed that this problem caused by `followSymlinks` option to set `false` because I wanted to do something a little special in the bundle work in my monorepo.

My use case has a repository structure like below.
There are `lib/worker` and `lib/web` sublayers by each tslib destination, each of which has its own packages.
As an important point, `lib/web` can reference `lib/worker` functionality, but not vice versa.

As a build work, bundle `lib/worker` to `framework/lib-worker` and `lib/web` to `framework/lib-web`.
In this time, a postscript runs for adjusting to reference that `framework/lib-web` can use `framework/lib-worker` instead of the packages in `lib/worker`.
To achieve this, it was convenient for me to intentionally set `followSymlinks: false`.

```
packages
 ├─ framework
 │          ├ lib-worker
 │          │
 │          ├ lib-web
 │
 └─ lib
       ├─ worker
       │    ├ pkg1
       │    ├ pkg2
       │    ├ pkg3
       │
       └─ web
             ├ pkg4
             ├ pkg5
```

In fact it works in v8.0.1, but in v8.1.1 it occur this error.
However if my use case can not supported, I might also consider making my postscript work with `followSymlinks: true`.

**Comment by Shin-Ogata** [comment]
I'm not sure, but it seems that `followSymlinks: false` also works for up to 2 levels.
It doesn't seem to work if there are 3 levels of dependencies.

As a specific example, there is a dependency relationship of `pkg_web` → `pkg_worker` → `pkg_core` as shown below.
in this case, it seems that `pkg_core` cannot be resolved if `followSimlinks: false`.

```
packages
 │
 └─ lib
       ├─ core
       │    ├ pkg_core
       │
       ├─ worker
       │    ├ pkg_worker
       │
       └─ web
             ├ pkg_web
                ├ node_modules/
                     ├ pkg_worker   ★ ← be resolved even in "followSimlinks: false"
                        ├ node_modules/
                           ├ pkg_core ★ ← cannot be resolved in "followSimlinks: false"
```

**Comment by Shin-Ogata** [comment]
> @Shin-Ogata is it possible to share your project/repro?

Since the original repository is too big,
I have prepared a reproduction environment with unnecessary parts removed in [dts-bundle-generator-survey](https://github.com/Shin-Ogata/dts-bundle-generator-survey).

What I learned while creating this repository is:
This issue appears to be caused by code that falls under [Known Limitations](https://github.com/timocov/dts-bundle-generator#known-limitations).
(I mentioned `followSimlinks` before, but I'm not sure if it's related.)

```ts
// rename case
import * as request from './request';
export { request };
```

I can accept that the output of this code is incorrect, but it's strange that after 8.1 it works or doesn't work depending on the situation.

### How to setup the repository

The reproduction environment construction method is as follows. This step will also properly install the sub-repository.

```sh
# after clone the repository
npm ci

# sub-repositry setup util
npm run packages:setup
```

### How to reproduce the issue

I have also prepared a script for reproduction steps. From root you can run:
```sh
npm run reproduce
# dts-bundle-generator --config ./packages/framework/lib-web/dts-bundle-config.js
```

#### Not reproduce situations

I use the same d.ts files, but for `lib-worker` bundle succeeds. This is not clear to me.

```sh
npm run not-reproduce
# dts-bundle-generator --config ./packages/framework/lib-worker/dts-bundle-config.js
```

As you know, even if you revert the dts-bundle-generator in package.json to v8.0.1 and follow the same steps, the issue does not reproduce.

----

I sincerely hope that you find this information useful.
Thanks.

**Comment by Shin-Ogata** [comment]
I found another error case, although it may be the same root.
The following cases apply to [extending the interface of an external module](https://github.com/Shin-Ogata/dts-bundle-generator-survey/blob/main/packages/lib/web/i18n/types/plugin/module-extends.d.ts#L1-L24).

```ts
import { i18n } from '@cdp/extension-i18n';

declare module '@cdp/extension-i18n' {
    namespace i18n {
        /**
         * @en {@link DomLocalizer} options interface.
         * @ja {@link DomLocalizer} のオプションインターフェイス
         */
        interface DomLocalizerOptions {
            /** selector for translating elements */
            selectorAttr?: string;
            /** data-() attribute to grab target element to translate (if different than itself) */
            targetAttr?: string;
            /** data-() attribute that contains options, will load/set if useOptionsAttr = true */
            optionsAttr?: string;
            /** see optionsAttr */
            useOptionsAttr?: boolean;
            /** parses default values from content ele.val or ele.text */
            parseDefaultValueFromContent?: boolean;
            /** `append` and `prepend` wrapper tag name */
            customTagName?: string | false;
        }
    }
}
```

You can also check this with the command below.

```sh
npm run reproduce2
# dts-bundle-generator --config ./packages/framework/lib-web2/dts-bundle-config.js
```

**Comment by timocov** [comment]
@Shin-Ogata thank you very much for the repro cases! It seems that `reproduce2` is related to the same issue as @wKovacs64 have, but `reproduce` is more interesting as it is related to the different issue, which I probably can fix without waiting for the response from the compiler team. I'll keep you posted here.

**Comment by timocov** [comment]
@Shin-Ogata For the first case I've created a separate issue https://github.com/timocov/dts-bundle-generator/issues/266 as I was able to reproduce it in v8.0 as well

**Comment by timocov** [comment]
The fix (for one of the problems) has been published https://github.com/timocov/dts-bundle-generator/releases/tag/v8.1.2
