### ISSUE TITLE
The exportElementSymbol occasionally returns undefined, resulting in an error in const namespaceImportForElement = getDeclarationsForSymbol(exportElementSymbol).find(ts.isNamespaceImport);.

### ISSUE THREAD

**Issue by Byte2Tech** [timocov/dts-bundle-generator#308]
https://github.com/timocov/dts-bundle-generator/blob/c092c03bdc2302483512c5d473362294848a2eb9/src/types-usage-evaluator.ts#L115

**Comment by timocov** [comment]
Do you have an example when this happens ñ

**Comment by Byte2Tech** [comment]
https://github.com/Byte2Tech/dts-bundle-generator-test

**Comment by timocov** [comment]
Hey @Byte2Tech,

I cannot use the provided repo directly because I have no access to https://registry.npm.alibaba-inc.com. After removing lock file, tweaking npmrc and yarnrc files, added `@types/node` and `@types/react` as dependencies, and adding `"types": ["react"],` to the tsconfig I was able to run `test.mjs` without any issues. Please provide exact steps to reproduce the issue.

**Comment by timocov** [comment]
Let me know if you have any updates on this.
