### ISSUE TITLE
Building typings for a project that imports Three.JS fails

### ISSUE THREAD

**Issue by rhuitl** [timocov/dts-bundle-generator#37]
I'm trying to build an amalgamated and flattened typings file with Three.JS as a dependency. I have narrowed down the problem to this minimal example. I would be very thankful for your help with this, the goal is to have a typings file for my own code and let it rely on typings from NPM for dependencies like Three.JS. I would rather not want to inline all the typings.

app.ts:
```ts
import {Vector3} from "three";

export function test(): Vector3 {
  return new Vector3();
}
```
package.json:
```json
{
  "name": "dts-bundle-generator-bugreport",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "npx tsc",
    "typings": "npx dts-bundle-generator -o app.d.ts app.ts"
  },
  "dependencies": {
    "three": "^0.93.0"
  },
  "devDependencies": {
    "dts-bundle-generator": "^1.2.2",
    "typescript": "^2.9.1",
    "@types/three": "^0.92.3"
  }
}
```
tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",
    "declaration": true,
    "lib": ["es2015", "dom"]
  }
}
```
Run:
```bash
npm install
npm run typings
```
Output:
```
Library "three" will be added via reference directive
Library "webvr-api" will be added via reference directive
Writing generated file to app.d.ts...
Checking the generated file...
app.d.ts(4,33): error TS2304: Cannot find name 'Vector3'.
Error: Compiled with errors
```
app.d.ts looks like:
```ts
/// <reference types="three" />
/// <reference types="webvr-api" />

export declare function test(): Vector3;
```

Question / bug (?): Why is the library added via reference, the documentation states "By default all libraries will be imported (except inlined)"? And why does the check fail? I'm not too familiar with the reference syntax, but I doubt that it makes the type `Vector3` available, so the check is probably right.

Next attempt: set `--external-imports` to a package name from `node_modules` to force the use of import:
```diff
-    "typings": "npx dts-bundle-generator -o app.d.ts app.ts"
+    "typings": "npx dts-bundle-generator -o app.d.ts --external-imports @types/three -- app.ts"
```

Exactly the same output as before. Next try:

```diff
-    "typings": "npx dts-bundle-generator -o app.d.ts app.ts"
+    "typings": "npx dts-bundle-generator -o app.d.ts --external-imports three -- app.ts"
```

Output:
```
Adding import with name "Vector3" for library "@types/three"
Library "webvr-api" will be added via reference directive
Writing generated file to app.d.ts...
Checking the generated file...
app.d.ts(3,25): error TS6137: Cannot import type declaration files. Consider importing 'three' instead of '@types/three'.
Error: Compiled with errors
```

app.d.ts:
```ts
/// <reference types="webvr-api" />

import { Vector3 } from '@types/three';

export declare function test(): Vector3;
```

Almost, it should indeed be `from 'three'` and not `from '@types/three'`.

**Comment by timocov** [comment]
Hi!

> Why is the library added via reference, the documentation states "By default all libraries will be imported (except inlined)"? 

It's correct behavior because this library has typing from `@types/` and that libraries has _additional_ special syntax to using (via triple-slash directive). So by default for such libraries I use this syntax instead of importing. But you can override this behavior via `--external-imports` (see #27) (and actually you did it).

> And why does the check fail? 

This happens because `three` package export `Vector3`, so you need to import this library instead of referencing it via `reference types` directive.

> so the check is probably right.

Yes, sure.

> it should indeed be from 'three' and not from '@types/three'.

Yes, you are absolutely right.

> Exactly the same output as before. Next try:

Actually this try should provide you correct typings, but there is a small bug. I'll fix it.

> Library "webvr-api" will be added via reference directive

This happens because typings for this library has extending the `Window` interface, so we cannot determine whether it is used in your typings or not (I'm not sure whether we can do it or not, but for now we don't). To prevent this you need to set `--external-types` to an empty array (or array without this library).

Thank you for reporting!
