### ISSUE TITLE
🐜 import default from namespace with esmoduleInterop true

### ISSUE THREAD

**Issue by bigopon** [timocov/dts-bundle-generator#62]
**Bug report**

**Input code**

There is an issue with import default from a namespace export, or module export related to `esModuleInterop: true`, and `--external-imports i18next`

```ts
import i18next from "i18next";

export class I18N {
  constructor(config: i18next.InitOptions) {

  }
}
```

**Output code**

```ts
import { InitOptions, i18next } from 'i18next';

export declare class I18N {
	constructor(config: i18next.InitOptions);
}
```

**Expected output**

```ts
import i18next from 'i18next';

export declare class I18N {
	constructor(config: i18next.InitOptions);
}
```

**Additional context**
  - flags: `--external-imports i18next`

**Comment by timocov** [comment]
Currently it's one of [limitations](https://github.com/timocov/dts-bundle-generator#known-limitations) of `dts-bundle-generator` (it isn't able to handle `import * as name` imports). I believe it should be fixed in #59.

For now I would suggest you use the following workaround:
```ts
import { InitOptions } from "i18next";

export class I18N {
  constructor(config: InitOptions) {}
}
```

This code is handled by `dts-bundle-generator` correctly and works the same as yours one.
