### ISSUE TITLE
Error after upgrading typescript to 3.7

### ISSUE THREAD

**Issue by houd1ni** [timocov/dts-bundle-generator#99]
Hi! Firstly, thank you for the utility - it's a lifesaver.

![image](https://user-images.githubusercontent.com/7501201/68292177-5b9aef00-009c-11ea-9e4a-d9aa66070dbd.png)

It's after upgrading typescript from ^3.6.4  to  ^3.7.2.
Downgrading fixed the issue.

Test repo: https://github.com/houd1ni/fela-vue
There's on commit # `1ffedf7cd323e74520a1eeea5754233a1431a808`  the problem can be reproduced by running `npm i & npm run test`

**Comment by timocov** [comment]
Hi @houd1ni,

> Firstly, thank you for the utility - it's a lifesaver.

I appreciate your feedback!

> It's after upgrading typescript from ^3.6.4 to ^3.7.2.

looks like your tsconfig doesn't have `"declaration": true,` compiler option. Quite possible that the TypeScript team had changed the behavior when you can emit declaration files without that option (previously it was possible, but there might be undefined behavior sometimes https://github.com/microsoft/TypeScript/issues/24002). I would recommend you add this option to your tsconfig to avoid this.

Regard putting this compiler option on by default in the tool under hood - I'm not sure that's good idea, because it _might_ produce strange errors (I'm not sure about now, but early you might have additional errors if you enable that option). But I haven't strong opinion here and it's possible that we need to enable it always.

**Comment by houd1ni** [comment]
It works, but we've got a new problem: useless files are emited in dist:
![image](https://user-images.githubusercontent.com/7501201/68323468-91f56000-00d6-11ea-883b-b1b74ce282d6.png)

**Comment by timocov** [comment]
https://github.com/microsoft/TypeScript/issues/24002#issuecomment-550549393 Looks like we must pass `declaration: true` if we want to generate declaration files.

**Comment by timocov** [comment]
[Version 3.3.0](https://www.npmjs.com/package/dts-bundle-generator/v/3.3.0) is just published!

**Comment by houd1ni** [comment]
@timocov  Does it emit useless declaration files after the update?

**Comment by timocov** [comment]
No, it shouldn't. `dts-bundle-generator` emits all outputs in-memory.

**Comment by timocov** [comment]
@houd1ni you can remove `declaration: true` from your tsconfig after upgrade, because `dts-bundle-generator` will enable it for you while generating bundle (and only).

**Comment by houd1ni** [comment]
It works. Thank you!
